COMMENT ON TABLE osm.natural_point IS 'Generated by osm2pgsql Flex output using pgosm/flex-config/road.lua';

ALTER TABLE osm.natural_point
	ADD CONSTRAINT pk_osm_rnatural_point_node_id
    PRIMARY KEY (node_id)
;

CREATE INDEX ix_osm_natural_point_type ON osm.natural_point (osm_type);
