COMMENT ON TABLE osm.road_major IS 'Generated by osm2pgsql Flex output using pgosm/flex-config/road.lua';
COMMENT ON COLUMN osm.road_line.road_major IS 'Value from "highway" key from OpenStreetMap data.  e.g. motorway, residential, etc.';

ALTER TABLE osm.road_major
	ADD CONSTRAINT pk_osm_road_major_way_id
    PRIMARY KEY (way_id)
;

CREATE INDEX ix_osm_road_major_type ON osm.road_major (osm_type);
